### ISSUE TITLE
CSS?

### ISSUE THREAD

**Issue by johannes-gehrs** [faucet-pipeline/docs#54]
The first sentence on the index page mentions:

> faucet-pipeline takes care of pre-processing CSS

But the link is a 404 and the SASS section mentions 

> faucet-pipeline currently only supports SCSS – CSS is still in beta

Not sure what the best state of affairs would be so I didn't do a PR but it definitely doesn't make too much sense the way it is now.

**Comment by moonglum** [comment]
Hello and welcome 😄 Yes, you are right, that doesn't make sense. The current state is:
* [faucet-pipeline-css](https://github.com/faucet-pipeline/faucet-pipeline-css) is still in beta
* We did not write documentation for it yet

IMHO, the right solution would be to add a CSS page that describes the in beta pipeline. What do you think?
